//! Implementation for `za gen`.

use anyhow::Result;
use std::{
    fs::File,
    io::{self, Write},
    path::{Path, PathBuf},
};

use crate::command::{lang_of, md_header, walk_workspace, BinaryFile, TextFile};

/// Entry for `za gen`
pub fn run(max_lines: usize, output: PathBuf, include_binary: bool) -> Result<()> {
    let (texts, bins) = walk_workspace(include_binary)?;
    write_context_md(&texts, &bins, max_lines, &output)?;
    println!("✅ Generated {}", output.display());
    Ok(())
}

/// Render `CONTEXT.md`
fn write_context_md(
    texts: &[TextFile],
    bins: &[BinaryFile],
    max: usize,
    out: &Path,
) -> io::Result<()> {
    let mut f = File::create(out)?;
    md_header(&mut f, "# 📚 Project Context — generated by za")?;

    // directory listing
    writeln!(f, "## 1. Directory Overview\n```text")?;
    for t in texts {
        writeln!(f, "({:<4}) {}", t.lines.len(), t.rel.display())?;
    }
    for b in bins {
        writeln!(f, "(bin ) {}", b.rel.display())?;
    }
    writeln!(f, "```\n")?;

    // code snippets
    writeln!(f, "## 2. File Snippets\n")?;
    for t in texts {
        writeln!(
            f,
            "<details><summary>{}</summary>\n\n```{}\n{}\n```\n</details>\n",
            t.rel.display(),
            lang_of(&t.rel),
            snippet(&t.lines, max)
        )?;
    }
    Ok(())
}

/// Truncate long files for preview
fn snippet(lines: &[String], max: usize) -> String {
    if lines.len() <= max {
        return lines.join("\n");
    }
    let half = max / 2;
    format!(
        "{}\n⋯(truncated)\n{}",
        lines[..half].join("\n"),
        lines[lines.len() - half..].join("\n")
    )
}
